/*
 * Safecast API
 *
 * Safecast API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Measurement {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "captured_at", skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<String>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<i64>,
    #[serde(rename = "device_id", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<i64>,
    #[serde(rename = "devicetype_id", skip_serializing_if = "Option::is_none")]
    pub devicetype_id: Option<i64>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(rename = "location_name", skip_serializing_if = "Option::is_none")]
    pub location_name: Option<String>,
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[serde(rename = "measurement_import_id", skip_serializing_if = "Option::is_none")]
    pub measurement_import_id: Option<i64>,
    #[serde(rename = "original_id", skip_serializing_if = "Option::is_none")]
    pub original_id: Option<i64>,
    #[serde(rename = "sensor_id", skip_serializing_if = "Option::is_none")]
    pub sensor_id: Option<i64>,
    #[serde(rename = "station_id", skip_serializing_if = "Option::is_none")]
    pub station_id: Option<i64>,
    #[serde(rename = "unit")]
    pub unit: String,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    #[serde(rename = "value")]
    pub value: i64,
}

impl Measurement {
    pub fn new(unit: String, value: i64) -> Measurement {
        Measurement {
            id: None,
            captured_at: None,
            channel_id: None,
            device_id: None,
            devicetype_id: None,
            height: None,
            latitude: None,
            location_name: None,
            longitude: None,
            measurement_import_id: None,
            original_id: None,
            sensor_id: None,
            station_id: None,
            unit,
            user_id: None,
            value,
        }
    }
}


