[package]
name = "os-utils"
version = "0.1.0"
authors = ["bgeorges"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gethostname = "0.2.1"
clap = "2.27.1" # from crates.io

[package]

